version: 2.1

jobs:
 build:
   machine:
    image: ubuntu-2204:2022.04.2
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     # build the application image
     - run: docker build -t dimejii/tstg:$CIRCLE_BRANCH .

     # save the image as a tar file
     - run: docker save dimejii/tstg:$CIRCLE_BRANCH -o my-image.tar

     # save the tar file as an artifact
     - store_artifacts:
         path: my-image.tar
         destination: my-image-artifact
